### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Krinkle** [js-reporters/js-reporters#7]
To be specified / known issues we want to address:

 - [ ] #3: Common API
     - [ ] method names
     - [ ] registration mechanism
     - [ ] #1: Common events/hooks
         - [x] event names (completed via PR #9)
         - [ ] format of event data
     - [ ] #4: Common test status
         - [ ] consistent terminology

**Comment by jzaefferer** [comment]
Closing in favor of remaining open issues.
